"""
Headless FPL auth via OAuth2 PKCE + Playwright.

Python port of:
  github.com/<user>/fpl-ai-assist/fpl-mcp-server/scripts/refresh-token.ts

The official `fpl` Python library uses the legacy email+password+cookie
flow which has been unreliable. This module drives a real Chromium
through FPL's PingOne/DaVinci OAuth provider and captures the
`X-Api-Authorization` JWT off the first authenticated /api/ request the
SPA makes after login.

USAGE — as a library:

    from fplstats.fpl_auth import refresh_token, get_valid_token

    # Returns a fresh token (refreshes if expired):
    token = await get_valid_token()
    headers = {"X-Api-Authorization": token, ...}

USAGE — as a CLI (via scripts/refresh_token.py):

    python scripts/refresh_token.py --save-credentials  # first-time setup
    python scripts/refresh_token.py                      # headless refresh

DEPENDENCIES:

    pip install -r requirements-auth.txt
    playwright install chromium

SECRETS LAYOUT — matches the TS reference:

    ~/.fpl/credentials.env   chmod 0600   FPL_EMAIL, FPL_PASSWORD
    ~/.fpl/secrets.env       chmod 0600   FPL_X_API_AUTH, FPL_MANAGER_ID

Per the global security policy, prefer macOS Keychain for storing
FPL_PASSWORD. A keychain-backed credential loader is provided as
`load_credentials_from_keychain()` — call it explicitly in your own
script if you want to bypass the env-file path.
"""
from __future__ import annotations

import asyncio
import base64
import hashlib
import json
import os
import re
import secrets
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional, Tuple
from urllib.parse import urlencode

# --- Constants matching the TS reference -----------------------------------

FPL_DIR = Path.home() / ".fpl"
CREDENTIALS_FILE = FPL_DIR / "credentials.env"
SECRETS_FILE = FPL_DIR / "secrets.env"

# DaVinci/PingOne client registered by FPL for the SPA. Static, not a secret.
CLIENT_ID = "bfcbaf69-aade-4c1b-8f00-c1cb8a193030"
REDIRECT_URI = "https://fantasy.premierleague.com/"
AUTHORIZE_URL = "https://account.premierleague.com/as/authorize"

FPL_HOMEPAGE = "https://fantasy.premierleague.com/"
FPL_MY_TEAM = "https://fantasy.premierleague.com/my-team"

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)


# --- Data classes ----------------------------------------------------------


@dataclass
class Credentials:
    email: str
    password: str


@dataclass
class Secrets:
    token: Optional[str] = None
    manager_id: Optional[str] = None


# --- File / secret helpers -------------------------------------------------


def _ensure_dir() -> None:
    FPL_DIR.mkdir(parents=True, exist_ok=True)


def load_credentials() -> Optional[Credentials]:
    """Read FPL_EMAIL / FPL_PASSWORD from ~/.fpl/credentials.env."""
    if not CREDENTIALS_FILE.exists():
        return None
    text = CREDENTIALS_FILE.read_text()
    email = _kv_match(text, "FPL_EMAIL")
    password = _kv_match(text, "FPL_PASSWORD")
    if email and password:
        return Credentials(email=email, password=password)
    return None


def load_credentials_from_keychain(
    email_account: str = "fpl-email",
    password_account: str = "fpl-password",
) -> Optional[Credentials]:
    """
    Load credentials from macOS Keychain. Returns None if either entry is
    missing. Store with:
        security add-generic-password -s 'fpl-email' -a "$USER" -w '<email>'
        security add-generic-password -s 'fpl-password' -a "$USER" -w '<pwd>'
    """
    email = _keychain_get(email_account)
    password = _keychain_get(password_account)
    if email and password:
        return Credentials(email=email, password=password)
    return None


def save_credentials(email: str, password: str) -> None:
    """Write credentials to ~/.fpl/credentials.env with chmod 0600."""
    _ensure_dir()
    content = (
        "# FPL credentials (auto-generated by fpl_auth)\n"
        "# chmod 0600 - only readable by owner\n"
        f"FPL_EMAIL={email}\n"
        f"FPL_PASSWORD={password}\n"
    )
    CREDENTIALS_FILE.write_text(content)
    os.chmod(CREDENTIALS_FILE, 0o600)


def load_secrets() -> Secrets:
    if not SECRETS_FILE.exists():
        return Secrets()
    text = SECRETS_FILE.read_text()
    return Secrets(
        token=_export_match(text, "FPL_X_API_AUTH"),
        manager_id=_export_match(text, "FPL_MANAGER_ID"),
    )


def save_secrets(token: str, manager_id: Optional[str]) -> None:
    """Write secrets to ~/.fpl/secrets.env with chmod 0600."""
    _ensure_dir()
    lines = [
        "# FPL Secrets (auto-generated by fpl_auth)",
        "# Re-run refresh_token.py when token expires",
        f'export FPL_X_API_AUTH="{token}"',
    ]
    if manager_id:
        lines.append(f'export FPL_MANAGER_ID="{manager_id}"')
    SECRETS_FILE.write_text("\n".join(lines) + "\n")
    os.chmod(SECRETS_FILE, 0o600)


def _kv_match(text: str, key: str) -> Optional[str]:
    m = re.search(rf"^{key}=(.+)$", text, flags=re.MULTILINE)
    return m.group(1) if m else None


def _export_match(text: str, key: str) -> Optional[str]:
    m = re.search(rf'export {key}="([^"]+)"', text)
    return m.group(1) if m else None


def _keychain_get(service: str) -> Optional[str]:
    try:
        out = subprocess.check_output(
            ["security", "find-generic-password", "-s", service, "-w"],
            stderr=subprocess.DEVNULL,
        )
        return out.decode().strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


# --- JWT helpers (no signature verification — that's the server's job) -----


def _decode_jwt_payload(token: str) -> dict:
    raw = token[7:] if token.startswith("Bearer ") else token
    parts = raw.split(".")
    if len(parts) < 2:
        return {}
    # Pad with '=' to make len % 4 == 0
    payload_b64 = parts[1] + "=" * (-len(parts[1]) % 4)
    try:
        return json.loads(base64.urlsafe_b64decode(payload_b64))
    except Exception:
        return {}


def get_token_expiry(token: str) -> Optional[datetime]:
    payload = _decode_jwt_payload(token)
    exp = payload.get("exp")
    return datetime.fromtimestamp(exp, tz=timezone.utc) if exp else None


def is_user_access_token(token: str) -> bool:
    """
    Reject DaVinci flow-bootstrap JWTs that the OAuth provider hands out
    while driving the login state machine. Those have
    usage=startSpecificFlowOrPolicyNonUserContext (or sub==aud) and are
    signed by a different JWKS than the FPL API trusts — using one yields
    `Unable to find a signing key that matches...` 401s.
    """
    payload = _decode_jwt_payload(token)
    if not payload:
        return False
    if payload.get("usage") == "startSpecificFlowOrPolicyNonUserContext":
        return False
    sub, aud = payload.get("sub"), payload.get("aud")
    if sub and aud and sub == aud:
        return False
    return True


def is_token_valid(token: str, leeway_seconds: int = 5 * 60) -> bool:
    """Token must be a user access token AND not expiring within `leeway_seconds`."""
    if not is_user_access_token(token):
        return False
    expiry = get_token_expiry(token)
    if not expiry:
        return False
    return expiry.timestamp() > time.time() + leeway_seconds


# --- PKCE ------------------------------------------------------------------


def _generate_pkce() -> Tuple[str, str, str]:
    """Returns (code_verifier, code_challenge, state)."""
    verifier = secrets.token_urlsafe(32)
    challenge = (
        base64.urlsafe_b64encode(hashlib.sha256(verifier.encode()).digest())
        .decode()
        .rstrip("=")
    )
    state = secrets.token_hex(16)
    return verifier, challenge, state


# --- Browser flow ----------------------------------------------------------


def _is_fpl_api_url(url: str) -> bool:
    """Only trust tokens seen on calls to the FPL resource server."""
    return "fantasy.premierleague.com/api/" in url


async def _drive_login(email: str, password: str) -> str:
    """
    Drive Chromium through the OAuth dance and return a captured JWT.
    Raises RuntimeError if no token is captured within the deadline.
    """
    # Lazy import — playwright is an opt-in dep.
    try:
        from playwright.async_api import async_playwright
    except ImportError as e:
        raise RuntimeError(
            "Playwright is not installed. Run:\n"
            "  pip install -r requirements-auth.txt\n"
            "  playwright install chromium"
        ) from e

    _, code_challenge, state = _generate_pkce()
    captured: dict = {"token": None}

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        try:
            context = await browser.new_context(user_agent=USER_AGENT)
            page = await context.new_page()

            def on_request(request):
                if captured["token"]:
                    return
                if not _is_fpl_api_url(request.url):
                    return
                hdrs = request.headers
                auth = hdrs.get("x-api-authorization") or hdrs.get("authorization")
                if not auth or "eyJ" not in auth:
                    return
                candidate = auth if auth.startswith("Bearer ") else f"Bearer {auth}"
                if not is_user_access_token(candidate):
                    return
                captured["token"] = candidate
                print("   token captured from FPL API request")

            page.on("request", on_request)

            print("navigating to FPL...")
            await page.goto(FPL_HOMEPAGE, wait_until="domcontentloaded", timeout=30_000)

            url = page.url
            if "account.premierleague.com" not in url:
                print("building OAuth2 PKCE login URL...")
                authorize = AUTHORIZE_URL + "?" + urlencode({
                    "client_id": CLIENT_ID,
                    "redirect_uri": REDIRECT_URI,
                    "response_type": "code",
                    "scope": "openid profile email offline_access",
                    "state": state,
                    "code_challenge": code_challenge,
                    "code_challenge_method": "S256",
                })
                await page.goto(authorize, wait_until="domcontentloaded", timeout=30_000)
                await page.wait_for_timeout(2000)
                url = page.url

            if "account.premierleague.com" in url or "users.premierleague.com" in url:
                print("login page detected, filling form...")
                await page.wait_for_timeout(2000)
                try:
                    await page.wait_for_selector("input", timeout=10_000)
                except Exception:
                    raise RuntimeError(f"no input fields found at {page.url}")

                # Try several email-field selectors before falling back to
                # "first visible input" — the OAuth provider has shipped
                # several login layouts.
                email_selectors = [
                    'input[placeholder*="mail"]',
                    'input[type="email"]',
                    'input[type="text"]',
                    'input[name="login"]',
                    'input[name="email"]',
                    'input[name="username"]',
                ]
                email_filled = False
                for sel in email_selectors:
                    try:
                        el = page.locator(sel).first
                        if await el.is_visible(timeout=1_000):
                            await el.fill(email)
                            email_filled = True
                            break
                    except Exception:
                        continue
                if not email_filled:
                    await page.locator("input:visible").first.fill(email)

                pwd = page.locator('input[type="password"]').first
                await pwd.wait_for(timeout=5_000)
                await pwd.fill(password)

                print("submitting login...")
                try:
                    submit = page.locator(
                        'button[type="submit"], input[type="submit"]'
                    ).first
                    if await submit.is_visible(timeout=2_000):
                        await submit.click()
                    else:
                        await pwd.press("Enter")
                except Exception:
                    await pwd.press("Enter")

                # After login the SPA reloads, completes its own handshake,
                # and fires authenticated /api/ calls. Our request listener
                # snatches the first user token off one of those.
                print("waiting for SPA to make an authenticated API call...")
                deadline = time.time() + 30
                while not captured["token"] and time.time() < deadline:
                    await page.wait_for_timeout(250)

                # Fallback: force /my-team if the SPA used a cached token.
                if not captured["token"]:
                    print("   no token yet, forcing /my-team...")
                    try:
                        await page.goto(
                            FPL_MY_TEAM, wait_until="domcontentloaded", timeout=30_000
                        )
                    except Exception:
                        pass
                    deadline2 = time.time() + 15
                    while not captured["token"] and time.time() < deadline2:
                        await page.wait_for_timeout(250)
        finally:
            await browser.close()

    if not captured["token"]:
        raise RuntimeError("failed to capture token — login likely failed")
    return captured["token"]


async def _fetch_manager_id(token: str) -> Optional[str]:
    """GET /api/me/ with the new token to discover the manager id."""
    try:
        import urllib.request
    except ImportError:
        return None
    req = urllib.request.Request(
        "https://fantasy.premierleague.com/api/me/",
        headers={"X-Api-Authorization": token, "User-Agent": USER_AGENT},
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310
            data = json.loads(resp.read())
        entry = data.get("player", {}).get("entry")
        return str(entry) if entry else None
    except Exception:
        return None


# --- Public API ------------------------------------------------------------


async def refresh_token(force: bool = False) -> str:
    """
    Refresh the FPL auth token if expired (or unconditionally if `force`).
    Persists the result to ~/.fpl/secrets.env and returns the token string
    (with the "Bearer " prefix).
    """
    existing = load_secrets()
    if not force and existing.token and is_token_valid(existing.token):
        expiry = get_token_expiry(existing.token)
        remaining = (expiry - datetime.now(tz=timezone.utc)).total_seconds()
        hours = int(remaining // 3600)
        minutes = int((remaining % 3600) // 60)
        print(f"token still valid (expires in {hours}h {minutes}m)")
        return existing.token

    credentials = load_credentials() or load_credentials_from_keychain()
    if not credentials:
        raise RuntimeError(
            "no credentials found. Run: python scripts/refresh_token.py --save-credentials"
        )

    print("refreshing FPL token headlessly...")
    token = await _drive_login(credentials.email, credentials.password)

    manager_id = existing.manager_id or await _fetch_manager_id(token)
    save_secrets(token, manager_id)

    expiry = get_token_expiry(token)
    print("token refreshed successfully")
    if expiry:
        remaining = (expiry - datetime.now(tz=timezone.utc)).total_seconds()
        hours = int(remaining // 3600)
        minutes = int((remaining % 3600) // 60)
        print(f"   expires: {expiry.isoformat()} ({hours}h {minutes}m)")
    if manager_id:
        print(f"   manager id: {manager_id}")
    print(f"   saved to: {SECRETS_FILE}")
    return token


async def get_valid_token() -> str:
    """
    Convenience wrapper: returns a valid token, refreshing if needed.
    Use this from fetch_league.py or any future API caller.
    """
    return await refresh_token(force=False)


# --- CLI entry point (also exposed via scripts/refresh_token.py) -----------


def _cli_save_credentials() -> None:
    print("Save FPL credentials")
    print("====================")
    print(f"Stored in {CREDENTIALS_FILE} (chmod 0600)\n")
    email = input("FPL email: ").strip()
    # Use getpass so the password isn't echoed.
    from getpass import getpass
    password = getpass("FPL password: ").strip()
    if not email or not password:
        print("email and password are required", file=sys.stderr)
        sys.exit(1)
    save_credentials(email, password)
    print(f"\ncredentials saved to {CREDENTIALS_FILE}")


def main() -> None:
    if "--save-credentials" in sys.argv:
        _cli_save_credentials()
        return
    force = "--force" in sys.argv
    asyncio.run(refresh_token(force=force))


if __name__ == "__main__":
    main()
